//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionsApp.PromotionsWebpart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class PromotionsWebpart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PromoItemsContainer;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(PromotionsWebpart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlPromoItemsContainer() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.PromoItemsContainer = @__ctrl;
            @__ctrl.ID = "PromoItemsContainer";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::PromotionsApp.PromotionsWebpart.PromotionsWebpart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf" +
                        "-8\" />\r\n<title>Untitled Document</title>\r\n\r\n<!-- Important Owl stylesheet -->\r\n " +
                        "   \r\n    <!--<link href=\"/_catalogs/masterpage/scripts/PromotionsSlider/owl-caro" +
                        "usel/owl.carousel.css\" rel=\"stylesheet\" />-->\r\n \r\n<!-- Default Theme -->\r\n\r\n<!--" +
                        "<link rel=\"stylesheet\" href=\"/_catalogs/masterpage/scripts/PromotionsSlider/owl-" +
                        "carousel/owl.theme.css\"/>-->\r\n \r\n<!--  jQuery 1.7+  -->\r\n<!--<script src=\"/_cata" +
                        "logs/masterpage/scripts/PromotionsSlider/assets/js/jquery-1.9.1.min.js\"></script" +
                        ">-->\r\n     \r\n \r\n<!-- Include js plugin -->\r\n<script src=\"/_catalogs/masterpage/s" +
                        "cripts/PromotionsSlider/owl-carousel/owl.carousel.js\"></script>\r\n<script id=\"owl" +
                        "carouseljs\" type=\"text/javascript\">\r\n    /*\r\n     *  jQuery OwlCarousel v1.3.3\r\n" +
                        "     *\r\n     *  Copyright (c) 2013 Bartosz Wojciechowski\r\n     *  http://www.owl" +
                        "graphic.com/owlcarousel/\r\n     *\r\n     *  Licensed under MIT\r\n     *\r\n     */\r\n\r" +
                        "\n    /*JS Lint helpers: */\r\n    /*global dragMove: false, dragEnd: false, $, jQu" +
                        "ery, alert, window, document */\r\n    /*jslint nomen: true, continue:true */\r\n\r\n " +
                        "   if (typeof Object.create !== \"function\") {\r\n        Object.create = function " +
                        "(obj) {\r\n            function F() { }\r\n            F.prototype = obj;\r\n         " +
                        "   return new F();\r\n        };\r\n    }\r\n    (function ($, window, document) {\r\n\r\n" +
                        "        var Carousel = {\r\n            init: function (options, el) {\r\n          " +
                        "      var base = this;\r\n\r\n                base.$elem = $(el);\r\n                b" +
                        "ase.options = $.extend({}, $.fn.owlCarousel.options, base.$elem.data(), options)" +
                        ";\r\n\r\n                base.userOptions = options;\r\n                base.loadConte" +
                        "nt();\r\n            },\r\n\r\n            loadContent: function () {\r\n               " +
                        " var base = this, url;\r\n\r\n                function getData(data) {\r\n            " +
                        "        var i, content = \"\";\r\n                    if (typeof base.options.jsonSu" +
                        "ccess === \"function\") {\r\n                        base.options.jsonSuccess.apply(" +
                        "this, [data]);\r\n                    } else {\r\n                        for (i in " +
                        "data.owl) {\r\n                            if (data.owl.hasOwnProperty(i)) {\r\n    " +
                        "                            content += data.owl[i].item;\r\n                      " +
                        "      }\r\n                        }\r\n                        base.$elem.html(cont" +
                        "ent);\r\n                    }\r\n                    base.logIn();\r\n               " +
                        " }\r\n\r\n                if (typeof base.options.beforeInit === \"function\") {\r\n    " +
                        "                base.options.beforeInit.apply(this, [base.$elem]);\r\n            " +
                        "    }\r\n\r\n                if (typeof base.options.jsonPath === \"string\") {\r\n     " +
                        "               url = base.options.jsonPath;\r\n                    $.getJSON(url, " +
                        "getData);\r\n                } else {\r\n                    base.logIn();\r\n        " +
                        "        }\r\n            },\r\n\r\n            logIn: function () {\r\n                v" +
                        "ar base = this;\r\n\r\n                base.$elem.data(\"owl-originalStyles\", base.$e" +
                        "lem.attr(\"style\"));\r\n                base.$elem.data(\"owl-originalClasses\", base" +
                        ".$elem.attr(\"class\"));\r\n\r\n                base.$elem.css({ opacity: 0 });\r\n     " +
                        "           base.orignalItems = base.options.items;\r\n                base.checkBr" +
                        "owser();\r\n                base.wrapperWidth = 0;\r\n                base.checkVisi" +
                        "ble = null;\r\n                base.setVars();\r\n            },\r\n\r\n            setV" +
                        "ars: function () {\r\n                var base = this;\r\n                if (base.$" +
                        "elem.children().length === 0) { return false; }\r\n                base.baseClass(" +
                        ");\r\n                base.eventTypes();\r\n                base.$userItems = base.$" +
                        "elem.children();\r\n                base.itemsAmount = base.$userItems.length;\r\n  " +
                        "              base.wrapItems();\r\n                base.$owlItems = base.$elem.fin" +
                        "d(\".owl-item\");\r\n                base.$owlWrapper = base.$elem.find(\".owl-wrappe" +
                        "r\");\r\n                base.playDirection = \"next\";\r\n                base.prevIte" +
                        "m = 0;\r\n                base.prevArr = [0];\r\n                base.currentItem = " +
                        "0;\r\n                base.customEvents();\r\n                base.onStartup();\r\n   " +
                        "         },\r\n\r\n            onStartup: function () {\r\n                var base = " +
                        "this;\r\n                base.updateItems();\r\n                base.calculateAll();" +
                        "\r\n                base.buildControls();\r\n                base.updateControls();\r" +
                        "\n                base.response();\r\n                base.moveEvents();\r\n         " +
                        "       base.stopOnHover();\r\n                base.owlStatus();\r\n\r\n               " +
                        " if (base.options.transitionStyle !== false) {\r\n                    base.transit" +
                        "ionTypes(base.options.transitionStyle);\r\n                }\r\n                if (" +
                        "base.options.autoPlay === true) {\r\n                    base.options.autoPlay = 5" +
                        "000;\r\n                }\r\n                base.play();\r\n\r\n                base.$e" +
                        "lem.find(\".owl-wrapper\").css(\"display\", \"block\");\r\n\r\n                if (!base.$" +
                        "elem.is(\":visible\")) {\r\n                    base.watchVisibility();\r\n           " +
                        "     } else {\r\n                    base.$elem.css(\"opacity\", 1);\r\n              " +
                        "  }\r\n                base.onstartup = false;\r\n                base.eachMoveUpdat" +
                        "e();\r\n                if (typeof base.options.afterInit === \"function\") {\r\n     " +
                        "               base.options.afterInit.apply(this, [base.$elem]);\r\n              " +
                        "  }\r\n            },\r\n\r\n            eachMoveUpdate: function () {\r\n              " +
                        "  var base = this;\r\n\r\n                if (base.options.lazyLoad === true) {\r\n   " +
                        "                 base.lazyLoad();\r\n                }\r\n                if (base.o" +
                        "ptions.autoHeight === true) {\r\n                    base.autoHeight();\r\n         " +
                        "       }\r\n                base.onVisibleItems();\r\n\r\n                if (typeof b" +
                        "ase.options.afterAction === \"function\") {\r\n                    base.options.afte" +
                        "rAction.apply(this, [base.$elem]);\r\n                }\r\n            },\r\n\r\n       " +
                        "     updateVars: function () {\r\n                var base = this;\r\n              " +
                        "  if (typeof base.options.beforeUpdate === \"function\") {\r\n                    ba" +
                        "se.options.beforeUpdate.apply(this, [base.$elem]);\r\n                }\r\n         " +
                        "       base.watchVisibility();\r\n                base.updateItems();\r\n           " +
                        "     base.calculateAll();\r\n                base.updatePosition();\r\n             " +
                        "   base.updateControls();\r\n                base.eachMoveUpdate();\r\n             " +
                        "   if (typeof base.options.afterUpdate === \"function\") {\r\n                    ba" +
                        "se.options.afterUpdate.apply(this, [base.$elem]);\r\n                }\r\n          " +
                        "  },\r\n\r\n            reload: function () {\r\n                var base = this;\r\n   " +
                        "             window.setTimeout(function () {\r\n                    base.updateVar" +
                        "s();\r\n                }, 0);\r\n            },\r\n\r\n            watchVisibility: fun" +
                        "ction () {\r\n                var base = this;\r\n\r\n                if (base.$elem.i" +
                        "s(\":visible\") === false) {\r\n                    base.$elem.css({ opacity: 0 });\r" +
                        "\n                    window.clearInterval(base.autoPlayInterval);\r\n             " +
                        "       window.clearInterval(base.checkVisible);\r\n                } else {\r\n     " +
                        "               return false;\r\n                }\r\n                base.checkVisib" +
                        "le = window.setInterval(function () {\r\n                    if (base.$elem.is(\":v" +
                        "isible\")) {\r\n                        base.reload();\r\n                        bas" +
                        "e.$elem.animate({ opacity: 1 }, 200);\r\n                        window.clearInter" +
                        "val(base.checkVisible);\r\n                    }\r\n                }, 500);\r\n      " +
                        "      },\r\n\r\n            wrapItems: function () {\r\n                var base = thi" +
                        "s;\r\n                base.$userItems.wrapAll(\"<div class=\\\"owl-wrapper\\\">\").wrap(" +
                        "\"<div class=\\\"owl-item\\\"></div>\");\r\n                base.$elem.find(\".owl-wrappe" +
                        "r\").wrap(\"<div class=\\\"owl-wrapper-outer\\\">\");\r\n                base.wrapperOute" +
                        "r = base.$elem.find(\".owl-wrapper-outer\");\r\n                base.$elem.css(\"disp" +
                        "lay\", \"block\");\r\n            },\r\n\r\n            baseClass: function () {\r\n       " +
                        "         var base = this,\r\n                    hasBaseClass = base.$elem.hasClas" +
                        "s(base.options.baseClass),\r\n                    hasThemeClass = base.$elem.hasCl" +
                        "ass(base.options.theme);\r\n\r\n                if (!hasBaseClass) {\r\n              " +
                        "      base.$elem.addClass(base.options.baseClass);\r\n                }\r\n\r\n       " +
                        "         if (!hasThemeClass) {\r\n                    base.$elem.addClass(base.opt" +
                        "ions.theme);\r\n                }\r\n            },\r\n\r\n            updateItems: func" +
                        "tion () {\r\n                var base = this, width, i;\r\n\r\n                if (bas" +
                        "e.options.responsive === false) {\r\n                    return false;\r\n          " +
                        "      }\r\n                if (base.options.singleItem === true) {\r\n              " +
                        "      base.options.items = base.orignalItems = 1;\r\n                    base.opti" +
                        "ons.itemsCustom = false;\r\n                    base.options.itemsDesktop = false;" +
                        "\r\n                    base.options.itemsDesktopSmall = false;\r\n                 " +
                        "   base.options.itemsTablet = false;\r\n                    base.options.itemsTabl" +
                        "etSmall = false;\r\n                    base.options.itemsMobile = false;\r\n       " +
                        "             return false;\r\n                }\r\n\r\n                width = $(base." +
                        "options.responsiveBaseWidth).width();\r\n\r\n                if (width > (base.optio" +
                        "ns.itemsDesktop[0] || base.orignalItems)) {\r\n                    base.options.it" +
                        "ems = base.orignalItems;\r\n                }\r\n                if (base.options.it" +
                        "emsCustom !== false) {\r\n                    //Reorder array by screen size\r\n    " +
                        "                base.options.itemsCustom.sort(function (a, b) { return a[0] - b[" +
                        "0]; });\r\n\r\n                    for (i = 0; i < base.options.itemsCustom.length; " +
                        "i += 1) {\r\n                        if (base.options.itemsCustom[i][0] <= width) " +
                        "{\r\n                            base.options.items = base.options.itemsCustom[i][" +
                        "1];\r\n                        }\r\n                    }\r\n\r\n                } else " +
                        "{\r\n\r\n                    if (width <= base.options.itemsDesktop[0] && base.optio" +
                        "ns.itemsDesktop !== false) {\r\n                        base.options.items = base." +
                        "options.itemsDesktop[1];\r\n                    }\r\n\r\n                    if (width" +
                        " <= base.options.itemsDesktopSmall[0] && base.options.itemsDesktopSmall !== fals" +
                        "e) {\r\n                        base.options.items = base.options.itemsDesktopSmal" +
                        "l[1];\r\n                    }\r\n\r\n                    if (width <= base.options.it" +
                        "emsTablet[0] && base.options.itemsTablet !== false) {\r\n                        b" +
                        "ase.options.items = base.options.itemsTablet[1];\r\n                    }\r\n\r\n     " +
                        "               if (width <= base.options.itemsTabletSmall[0] && base.options.ite" +
                        "msTabletSmall !== false) {\r\n                        base.options.items = base.op" +
                        "tions.itemsTabletSmall[1];\r\n                    }\r\n\r\n                    if (wid" +
                        "th <= base.options.itemsMobile[0] && base.options.itemsMobile !== false) {\r\n    " +
                        "                    base.options.items = base.options.itemsMobile[1];\r\n         " +
                        "           }\r\n                }\r\n\r\n                //if number of items is less " +
                        "than declared\r\n                if (base.options.items > base.itemsAmount && base" +
                        ".options.itemsScaleUp === true) {\r\n                    base.options.items = base" +
                        ".itemsAmount;\r\n                }\r\n            },\r\n\r\n            response: functi" +
                        "on () {\r\n                var base = this,\r\n                    smallDelay,\r\n    " +
                        "                lastWindowWidth;\r\n\r\n                if (base.options.responsive " +
                        "!== true) {\r\n                    return false;\r\n                }\r\n             " +
                        "   lastWindowWidth = $(window).width();\r\n\r\n                base.resizer = functi" +
                        "on () {\r\n                    if ($(window).width() !== lastWindowWidth) {\r\n     " +
                        "                   if (base.options.autoPlay !== false) {\r\n                     " +
                        "       window.clearInterval(base.autoPlayInterval);\r\n                        }\r\n" +
                        "                        window.clearTimeout(smallDelay);\r\n                      " +
                        "  smallDelay = window.setTimeout(function () {\r\n                            last" +
                        "WindowWidth = $(window).width();\r\n                            base.updateVars();" +
                        "\r\n                        }, base.options.responsiveRefreshRate);\r\n             " +
                        "       }\r\n                };\r\n                $(window).resize(base.resizer);\r\n " +
                        "           },\r\n\r\n            updatePosition: function () {\r\n                var " +
                        "base = this;\r\n                base.jumpTo(base.currentItem);\r\n                if" +
                        " (base.options.autoPlay !== false) {\r\n                    base.checkAp();\r\n     " +
                        "           }\r\n            },\r\n\r\n            appendItemsSizes: function () {\r\n   " +
                        "             var base = this,\r\n                    roundPages = 0,\r\n            " +
                        "        lastItem = base.itemsAmount - base.options.items;\r\n\r\n                bas" +
                        "e.$owlItems.each(function (index) {\r\n                    var $this = $(this);\r\n " +
                        "                   $this\r\n                        .css({ \"width\": base.itemWidth" +
                        " })\r\n                        .data(\"owl-item\", Number(index));\r\n\r\n              " +
                        "      if (index % base.options.items === 0 || index === lastItem) {\r\n           " +
                        "             if (!(index > lastItem)) {\r\n                            roundPages " +
                        "+= 1;\r\n                        }\r\n                    }\r\n                    $th" +
                        "is.data(\"owl-roundPages\", roundPages);\r\n                });\r\n            },\r\n\r\n " +
                        "           appendWrapperSizes: function () {\r\n                var base = this,\r\n" +
                        "                    width = base.$owlItems.length * base.itemWidth;\r\n\r\n         " +
                        "       base.$owlWrapper.css({\r\n                    \"width\": width * 2,\r\n        " +
                        "            \"left\": 0\r\n                });\r\n                base.appendItemsSize" +
                        "s();\r\n            },\r\n\r\n            calculateAll: function () {\r\n               " +
                        " var base = this;\r\n                base.calculateWidth();\r\n                base." +
                        "appendWrapperSizes();\r\n                base.loops();\r\n                base.max()" +
                        ";\r\n            },\r\n\r\n            calculateWidth: function () {\r\n                " +
                        "var base = this;\r\n                base.itemWidth = Math.round(base.$elem.width()" +
                        " / base.options.items);\r\n            },\r\n\r\n            max: function () {\r\n     " +
                        "           var base = this,\r\n                    maximum = ((base.itemsAmount * " +
                        "base.itemWidth) - base.options.items * base.itemWidth) * -1;\r\n                if" +
                        " (base.options.items > base.itemsAmount) {\r\n                    base.maximumItem" +
                        " = 0;\r\n                    maximum = 0;\r\n                    base.maximumPixels " +
                        "= 0;\r\n                } else {\r\n                    base.maximumItem = base.item" +
                        "sAmount - base.options.items;\r\n                    base.maximumPixels = maximum;" +
                        "\r\n                }\r\n                return maximum;\r\n            },\r\n\r\n        " +
                        "    min: function () {\r\n                return 0;\r\n            },\r\n\r\n           " +
                        " loops: function () {\r\n                var base = this,\r\n                    pre" +
                        "v = 0,\r\n                    elWidth = 0,\r\n                    i,\r\n              " +
                        "      item,\r\n                    roundPageNum;\r\n\r\n                base.positions" +
                        "InArray = [0];\r\n                base.pagesInArray = [];\r\n\r\n                for (" +
                        "i = 0; i < base.itemsAmount; i += 1) {\r\n                    elWidth += base.item" +
                        "Width;\r\n                    base.positionsInArray.push(-elWidth);\r\n\r\n           " +
                        "         if (base.options.scrollPerPage === true) {\r\n                        ite" +
                        "m = $(base.$owlItems[i]);\r\n                        roundPageNum = item.data(\"owl" +
                        "-roundPages\");\r\n                        if (roundPageNum !== prev) {\r\n          " +
                        "                  base.pagesInArray[prev] = base.positionsInArray[i];\r\n         " +
                        "                   prev = roundPageNum;\r\n                        }\r\n            " +
                        "        }\r\n                }\r\n            },\r\n\r\n            buildControls: funct" +
                        "ion () {\r\n                var base = this;\r\n                if (base.options.nav" +
                        "igation === true || base.options.pagination === true) {\r\n                    bas" +
                        "e.owlControls = $(\"<div class=\\\"owl-controls\\\"/>\").toggleClass(\"clickable\", !bas" +
                        "e.browser.isTouch).appendTo(base.$elem);\r\n                }\r\n                if " +
                        "(base.options.pagination === true) {\r\n                    base.buildPagination()" +
                        ";\r\n                }\r\n                if (base.options.navigation === true) {\r\n " +
                        "                   base.buildButtons();\r\n                }\r\n            },\r\n\r\n  " +
                        "          buildButtons: function () {\r\n                var base = this,\r\n       " +
                        "             buttonsWrapper = $(\"<div class=\\\"owl-buttons\\\"/>\");\r\n              " +
                        "  base.owlControls.append(buttonsWrapper);\r\n\r\n                base.buttonPrev = " +
                        "$(\"<div/>\", {\r\n                    \"class\": \"owl-prev\",\r\n                    \"ht" +
                        "ml\": base.options.navigationText[0] || \"\"\r\n                });\r\n\r\n              " +
                        "  base.buttonNext = $(\"<div/>\", {\r\n                    \"class\": \"owl-next\",\r\n   " +
                        "                 \"html\": base.options.navigationText[1] || \"\"\r\n                }" +
                        ");\r\n\r\n                buttonsWrapper\r\n                    .append(base.buttonPre" +
                        "v)\r\n                    .append(base.buttonNext);\r\n\r\n                buttonsWrap" +
                        "per.on(\"touchstart.owlControls mousedown.owlControls\", \"div[class^=\\\"owl\\\"]\", fu" +
                        "nction (event) {\r\n                    event.preventDefault();\r\n                }" +
                        ");\r\n\r\n                buttonsWrapper.on(\"touchend.owlControls mouseup.owlControl" +
                        "s\", \"div[class^=\\\"owl\\\"]\", function (event) {\r\n                    event.prevent" +
                        "Default();\r\n                    if ($(this).hasClass(\"owl-next\")) {\r\n           " +
                        "             base.next();\r\n                    } else {\r\n                       " +
                        " base.prev();\r\n                    }\r\n                });\r\n            },\r\n\r\n   " +
                        "         buildPagination: function () {\r\n                var base = this;\r\n\r\n   " +
                        "             base.paginationWrapper = $(\"<div class=\\\"owl-pagination\\\"/>\");\r\n   " +
                        "             base.owlControls.append(base.paginationWrapper);\r\n\r\n               " +
                        " base.paginationWrapper.on(\"touchend.owlControls mouseup.owlControls\", \".owl-pag" +
                        "e\", function (event) {\r\n                    event.preventDefault();\r\n           " +
                        "         if (Number($(this).data(\"owl-page\")) !== base.currentItem) {\r\n         " +
                        "               base.goTo(Number($(this).data(\"owl-page\")), true);\r\n             " +
                        "       }\r\n                });\r\n            },\r\n\r\n            updatePagination: f" +
                        "unction () {\r\n                var base = this,\r\n                    counter,\r\n  " +
                        "                  lastPage,\r\n                    lastItem,\r\n                    " +
                        "i,\r\n                    paginationButton,\r\n                    paginationButtonI" +
                        "nner;\r\n\r\n                if (base.options.pagination === false) {\r\n             " +
                        "       return false;\r\n                }\r\n\r\n                base.paginationWrappe" +
                        "r.html(\"\");\r\n\r\n                counter = 0;\r\n                lastPage = base.ite" +
                        "msAmount - base.itemsAmount % base.options.items;\r\n\r\n                for (i = 0;" +
                        " i < base.itemsAmount; i += 1) {\r\n                    if (i % base.options.items" +
                        " === 0) {\r\n                        counter += 1;\r\n                        if (la" +
                        "stPage === i) {\r\n                            lastItem = base.itemsAmount - base." +
                        "options.items;\r\n                        }\r\n                        paginationBut" +
                        "ton = $(\"<div/>\", {\r\n                            \"class\": \"owl-page\"\r\n          " +
                        "              });\r\n                        paginationButtonInner = $(\"<span></sp" +
                        "an>\", {\r\n                            \"text\": base.options.paginationNumbers === " +
                        "true ? counter : \"\",\r\n                            \"class\": base.options.paginati" +
                        "onNumbers === true ? \"owl-numbers\" : \"\"\r\n                        });\r\n          " +
                        "              paginationButton.append(paginationButtonInner);\r\n\r\n               " +
                        "         paginationButton.data(\"owl-page\", lastPage === i ? lastItem : i);\r\n    " +
                        "                    paginationButton.data(\"owl-roundPages\", counter);\r\n\r\n       " +
                        "                 base.paginationWrapper.append(paginationButton);\r\n             " +
                        "       }\r\n                }\r\n                base.checkPagination();\r\n          " +
                        "  },\r\n            checkPagination: function () {\r\n                var base = thi" +
                        "s;\r\n                if (base.options.pagination === false) {\r\n                  " +
                        "  return false;\r\n                }\r\n                base.paginationWrapper.find(" +
                        "\".owl-page\").each(function () {\r\n                    if ($(this).data(\"owl-round" +
                        "Pages\") === $(base.$owlItems[base.currentItem]).data(\"owl-roundPages\")) {\r\n     " +
                        "                   base.paginationWrapper\r\n                            .find(\".o" +
                        "wl-page\")\r\n                            .removeClass(\"active\");\r\n                " +
                        "        $(this).addClass(\"active\");\r\n                    }\r\n                });\r" +
                        "\n            },\r\n\r\n            checkNavigation: function () {\r\n                v" +
                        "ar base = this;\r\n\r\n                if (base.options.navigation === false) {\r\n   " +
                        "                 return false;\r\n                }\r\n                if (base.opti" +
                        "ons.rewindNav === false) {\r\n                    if (base.currentItem === 0 && ba" +
                        "se.maximumItem === 0) {\r\n                        base.buttonPrev.addClass(\"disab" +
                        "led\");\r\n                        base.buttonNext.addClass(\"disabled\");\r\n         " +
                        "           } else if (base.currentItem === 0 && base.maximumItem !== 0) {\r\n     " +
                        "                   base.buttonPrev.addClass(\"disabled\");\r\n                      " +
                        "  base.buttonNext.removeClass(\"disabled\");\r\n                    } else if (base." +
                        "currentItem === base.maximumItem) {\r\n                        base.buttonPrev.rem" +
                        "oveClass(\"disabled\");\r\n                        base.buttonNext.addClass(\"disable" +
                        "d\");\r\n                    } else if (base.currentItem !== 0 && base.currentItem " +
                        "!== base.maximumItem) {\r\n                        base.buttonPrev.removeClass(\"di" +
                        "sabled\");\r\n                        base.buttonNext.removeClass(\"disabled\");\r\n   " +
                        "                 }\r\n                }\r\n            },\r\n\r\n            updateContr" +
                        "ols: function () {\r\n                var base = this;\r\n                base.updat" +
                        "ePagination();\r\n                base.checkNavigation();\r\n                if (bas" +
                        "e.owlControls) {\r\n                    if (base.options.items >= base.itemsAmount" +
                        ") {\r\n                        base.owlControls.hide();\r\n                    } els" +
                        "e {\r\n                        base.owlControls.show();\r\n                    }\r\n  " +
                        "              }\r\n            },\r\n\r\n            destroyControls: function () {\r\n " +
                        "               var base = this;\r\n                if (base.owlControls) {\r\n      " +
                        "              base.owlControls.remove();\r\n                }\r\n            },\r\n\r\n " +
                        "           next: function (speed) {\r\n                var base = this;\r\n\r\n       " +
                        "         if (base.isTransition) {\r\n                    return false;\r\n          " +
                        "      }\r\n\r\n                base.currentItem += base.options.scrollPerPage === tr" +
                        "ue ? base.options.items : 1;\r\n                if (base.currentItem > base.maximu" +
                        "mItem + (base.options.scrollPerPage === true ? (base.options.items - 1) : 0)) {\r" +
                        "\n                    if (base.options.rewindNav === true) {\r\n                   " +
                        "     base.currentItem = 0;\r\n                        speed = \"rewind\";\r\n         " +
                        "           } else {\r\n                        base.currentItem = base.maximumItem" +
                        ";\r\n                        return false;\r\n                    }\r\n               " +
                        " }\r\n                base.goTo(base.currentItem, speed);\r\n            },\r\n\r\n     " +
                        "       prev: function (speed) {\r\n                var base = this;\r\n\r\n           " +
                        "     if (base.isTransition) {\r\n                    return false;\r\n              " +
                        "  }\r\n\r\n                if (base.options.scrollPerPage === true && base.currentIt" +
                        "em > 0 && base.currentItem < base.options.items) {\r\n                    base.cur" +
                        "rentItem = 0;\r\n                } else {\r\n                    base.currentItem -=" +
                        " base.options.scrollPerPage === true ? base.options.items : 1;\r\n                " +
                        "}\r\n                if (base.currentItem < 0) {\r\n                    if (base.opt" +
                        "ions.rewindNav === true) {\r\n                        base.currentItem = base.maxi" +
                        "mumItem;\r\n                        speed = \"rewind\";\r\n                    } else " +
                        "{\r\n                        base.currentItem = 0;\r\n                        return" +
                        " false;\r\n                    }\r\n                }\r\n                base.goTo(bas" +
                        "e.currentItem, speed);\r\n            },\r\n\r\n            goTo: function (position, " +
                        "speed, drag) {\r\n                var base = this,\r\n                    goToPixel;" +
                        "\r\n\r\n                if (base.isTransition) {\r\n                    return false;\r" +
                        "\n                }\r\n                if (typeof base.options.beforeMove === \"func" +
                        "tion\") {\r\n                    base.options.beforeMove.apply(this, [base.$elem]);" +
                        "\r\n                }\r\n                if (position >= base.maximumItem) {\r\n      " +
                        "              position = base.maximumItem;\r\n                } else if (position " +
                        "<= 0) {\r\n                    position = 0;\r\n                }\r\n\r\n               " +
                        " base.currentItem = base.owl.currentItem = position;\r\n                if (base.o" +
                        "ptions.transitionStyle !== false && drag !== \"drag\" && base.options.items === 1 " +
                        "&& base.browser.support3d === true) {\r\n                    base.swapSpeed(0);\r\n " +
                        "                   if (base.browser.support3d === true) {\r\n                     " +
                        "   base.transition3d(base.positionsInArray[position]);\r\n                    } el" +
                        "se {\r\n                        base.css2slide(base.positionsInArray[position], 1)" +
                        ";\r\n                    }\r\n                    base.afterGo();\r\n                 " +
                        "   base.singleItemTransition();\r\n                    return false;\r\n            " +
                        "    }\r\n                goToPixel = base.positionsInArray[position];\r\n\r\n         " +
                        "       if (base.browser.support3d === true) {\r\n                    base.isCss3Fi" +
                        "nish = false;\r\n\r\n                    if (speed === true) {\r\n                    " +
                        "    base.swapSpeed(\"paginationSpeed\");\r\n                        window.setTimeou" +
                        "t(function () {\r\n                            base.isCss3Finish = true;\r\n        " +
                        "                }, base.options.paginationSpeed);\r\n\r\n                    } else " +
                        "if (speed === \"rewind\") {\r\n                        base.swapSpeed(base.options.r" +
                        "ewindSpeed);\r\n                        window.setTimeout(function () {\r\n         " +
                        "                   base.isCss3Finish = true;\r\n                        }, base.op" +
                        "tions.rewindSpeed);\r\n\r\n                    } else {\r\n                        bas" +
                        "e.swapSpeed(\"slideSpeed\");\r\n                        window.setTimeout(function (" +
                        ") {\r\n                            base.isCss3Finish = true;\r\n                    " +
                        "    }, base.options.slideSpeed);\r\n                    }\r\n                    bas" +
                        "e.transition3d(goToPixel);\r\n                } else {\r\n                    if (sp" +
                        "eed === true) {\r\n                        base.css2slide(goToPixel, base.options." +
                        "paginationSpeed);\r\n                    } else if (speed === \"rewind\") {\r\n       " +
                        "                 base.css2slide(goToPixel, base.options.rewindSpeed);\r\n         " +
                        "           } else {\r\n                        base.css2slide(goToPixel, base.opti" +
                        "ons.slideSpeed);\r\n                    }\r\n                }\r\n                base" +
                        ".afterGo();\r\n            },\r\n\r\n            jumpTo: function (position) {\r\n      " +
                        "          var base = this;\r\n                if (typeof base.options.beforeMove =" +
                        "== \"function\") {\r\n                    base.options.beforeMove.apply(this, [base." +
                        "$elem]);\r\n                }\r\n                if (position >= base.maximumItem ||" +
                        " position === -1) {\r\n                    position = base.maximumItem;\r\n         " +
                        "       } else if (position <= 0) {\r\n                    position = 0;\r\n         " +
                        "       }\r\n                base.swapSpeed(0);\r\n                if (base.browser.s" +
                        "upport3d === true) {\r\n                    base.transition3d(base.positionsInArra" +
                        "y[position]);\r\n                } else {\r\n                    base.css2slide(base" +
                        ".positionsInArray[position], 1);\r\n                }\r\n                base.curren" +
                        "tItem = base.owl.currentItem = position;\r\n                base.afterGo();\r\n     " +
                        "       },\r\n\r\n            afterGo: function () {\r\n                var base = this" +
                        ";\r\n\r\n                base.prevArr.push(base.currentItem);\r\n                base." +
                        "prevItem = base.owl.prevItem = base.prevArr[base.prevArr.length - 2];\r\n         " +
                        "       base.prevArr.shift(0);\r\n\r\n                if (base.prevItem !== base.curr" +
                        "entItem) {\r\n                    base.checkPagination();\r\n                    bas" +
                        "e.checkNavigation();\r\n                    base.eachMoveUpdate();\r\n\r\n            " +
                        "        if (base.options.autoPlay !== false) {\r\n                        base.che" +
                        "ckAp();\r\n                    }\r\n                }\r\n                if (typeof ba" +
                        "se.options.afterMove === \"function\" && base.prevItem !== base.currentItem) {\r\n  " +
                        "                  base.options.afterMove.apply(this, [base.$elem]);\r\n           " +
                        "     }\r\n            },\r\n\r\n            stop: function () {\r\n                var b" +
                        "ase = this;\r\n                base.apStatus = \"stop\";\r\n                window.cle" +
                        "arInterval(base.autoPlayInterval);\r\n            },\r\n\r\n            checkAp: funct" +
                        "ion () {\r\n                var base = this;\r\n                if (base.apStatus !=" +
                        "= \"stop\") {\r\n                    base.play();\r\n                }\r\n            }," +
                        "\r\n\r\n            play: function () {\r\n                var base = this;\r\n         " +
                        "       base.apStatus = \"play\";\r\n                if (base.options.autoPlay === fa" +
                        "lse) {\r\n                    return false;\r\n                }\r\n                wi" +
                        "ndow.clearInterval(base.autoPlayInterval);\r\n                base.autoPlayInterva" +
                        "l = window.setInterval(function () {\r\n                    base.next(true);\r\n    " +
                        "            }, base.options.autoPlay);\r\n            },\r\n\r\n            swapSpeed:" +
                        " function (action) {\r\n                var base = this;\r\n                if (acti" +
                        "on === \"slideSpeed\") {\r\n                    base.$owlWrapper.css(base.addCssSpee" +
                        "d(base.options.slideSpeed));\r\n                } else if (action === \"paginationS" +
                        "peed\") {\r\n                    base.$owlWrapper.css(base.addCssSpeed(base.options" +
                        ".paginationSpeed));\r\n                } else if (typeof action !== \"string\") {\r\n " +
                        "                   base.$owlWrapper.css(base.addCssSpeed(action));\r\n            " +
                        "    }\r\n            },\r\n\r\n            addCssSpeed: function (speed) {\r\n          " +
                        "      return {\r\n                    \"-webkit-transition\": \"all \" + speed + \"ms e" +
                        "ase\",\r\n                    \"-moz-transition\": \"all \" + speed + \"ms ease\",\r\n     " +
                        "               \"-o-transition\": \"all \" + speed + \"ms ease\",\r\n                   " +
                        " \"transition\": \"all \" + speed + \"ms ease\"\r\n                };\r\n            },\r\n\r" +
                        "\n            removeTransition: function () {\r\n                return {\r\n        " +
                        "            \"-webkit-transition\": \"\",\r\n                    \"-moz-transition\": \"\"" +
                        ",\r\n                    \"-o-transition\": \"\",\r\n                    \"transition\": \"" +
                        "\"\r\n                };\r\n            },\r\n\r\n            doTranslate: function (pixe" +
                        "ls) {\r\n                return {\r\n                    \"-webkit-transform\": \"trans" +
                        "late3d(\" + pixels + \"px, 0px, 0px)\",\r\n                    \"-moz-transform\": \"tra" +
                        "nslate3d(\" + pixels + \"px, 0px, 0px)\",\r\n                    \"-o-transform\": \"tra" +
                        "nslate3d(\" + pixels + \"px, 0px, 0px)\",\r\n                    \"-ms-transform\": \"tr" +
                        "anslate3d(\" + pixels + \"px, 0px, 0px)\",\r\n                    \"transform\": \"trans" +
                        "late3d(\" + pixels + \"px, 0px,0px)\"\r\n                };\r\n            },\r\n\r\n      " +
                        "      transition3d: function (value) {\r\n                var base = this;\r\n      " +
                        "          base.$owlWrapper.css(base.doTranslate(value));\r\n            },\r\n\r\n    " +
                        "        css2move: function (value) {\r\n                var base = this;\r\n        " +
                        "        base.$owlWrapper.css({ \"left\": value });\r\n            },\r\n\r\n            " +
                        "css2slide: function (value, speed) {\r\n                var base = this;\r\n\r\n      " +
                        "          base.isCssFinish = false;\r\n                base.$owlWrapper.stop(true," +
                        " true).animate({\r\n                    \"left\": value\r\n                }, {\r\n     " +
                        "               duration: speed || base.options.slideSpeed,\r\n                    " +
                        "complete: function () {\r\n                        base.isCssFinish = true;\r\n     " +
                        "               }\r\n                });\r\n            },\r\n\r\n            checkBrowse" +
                        "r: function () {\r\n                var base = this,\r\n                    translat" +
                        "e3D = \"translate3d(0px, 0px, 0px)\",\r\n                    tempElem = document.cre" +
                        "ateElement(\"div\"),\r\n                    regex,\r\n                    asSupport,\r\n" +
                        "                    support3d,\r\n                    isTouch;\r\n\r\n                " +
                        "tempElem.style.cssText = \"  -moz-transform:\" + translate3D +\r\n                  " +
                        "                    \"; -ms-transform:\" + translate3D +\r\n                        " +
                        "              \"; -o-transform:\" + translate3D +\r\n                               " +
                        "       \"; -webkit-transform:\" + translate3D +\r\n                                 " +
                        "     \"; transform:\" + translate3D;\r\n                regex = /translate3d\\(0px, 0" +
                        "px, 0px\\)/g;\r\n                asSupport = tempElem.style.cssText.match(regex);\r\n" +
                        "                support3d = (asSupport !== null && asSupport.length === 1);\r\n\r\n " +
                        "               isTouch = \"ontouchstart\" in window || window.navigator.msMaxTouch" +
                        "Points;\r\n\r\n                base.browser = {\r\n                    \"support3d\": su" +
                        "pport3d,\r\n                    \"isTouch\": isTouch\r\n                };\r\n          " +
                        "  },\r\n\r\n            moveEvents: function () {\r\n                var base = this;\r" +
                        "\n                if (base.options.mouseDrag !== false || base.options.touchDrag " +
                        "!== false) {\r\n                    base.gestures();\r\n                    base.dis" +
                        "abledEvents();\r\n                }\r\n            },\r\n\r\n            eventTypes: fun" +
                        "ction () {\r\n                var base = this,\r\n                    types = [\"s\", " +
                        "\"e\", \"x\"];\r\n\r\n                base.ev_types = {};\r\n\r\n                if (base.op" +
                        "tions.mouseDrag === true && base.options.touchDrag === true) {\r\n                " +
                        "    types = [\r\n                        \"touchstart.owl mousedown.owl\",\r\n        " +
                        "                \"touchmove.owl mousemove.owl\",\r\n                        \"touchen" +
                        "d.owl touchcancel.owl mouseup.owl\"\r\n                    ];\r\n                } el" +
                        "se if (base.options.mouseDrag === false && base.options.touchDrag === true) {\r\n " +
                        "                   types = [\r\n                        \"touchstart.owl\",\r\n       " +
                        "                 \"touchmove.owl\",\r\n                        \"touchend.owl touchca" +
                        "ncel.owl\"\r\n                    ];\r\n                } else if (base.options.mouse" +
                        "Drag === true && base.options.touchDrag === false) {\r\n                    types " +
                        "= [\r\n                        \"mousedown.owl\",\r\n                        \"mousemov" +
                        "e.owl\",\r\n                        \"mouseup.owl\"\r\n                    ];\r\n        " +
                        "        }\r\n\r\n                base.ev_types.start = types[0];\r\n                ba" +
                        "se.ev_types.move = types[1];\r\n                base.ev_types.end = types[2];\r\n   " +
                        "         },\r\n\r\n            disabledEvents: function () {\r\n                var ba" +
                        "se = this;\r\n                base.$elem.on(\"dragstart.owl\", function (event) { ev" +
                        "ent.preventDefault(); });\r\n                base.$elem.on(\"mousedown.disableTextS" +
                        "elect\", function (e) {\r\n                    return $(e.target).is(\'input, textar" +
                        "ea, select, option\');\r\n                });\r\n            },\r\n\r\n            gestur" +
                        "es: function () {\r\n                /*jslint unparam: true*/\r\n                var" +
                        " base = this,\r\n                    locals = {\r\n                        offsetX: " +
                        "0,\r\n                        offsetY: 0,\r\n                        baseElWidth: 0," +
                        "\r\n                        relativePos: 0,\r\n                        position: nul" +
                        "l,\r\n                        minSwipe: null,\r\n                        maxSwipe: n" +
                        "ull,\r\n                        sliding: null,\r\n                        dargging: " +
                        "null,\r\n                        targetElement: null\r\n                    };\r\n\r\n  " +
                        "              base.isCssFinish = true;\r\n\r\n                function getTouches(ev" +
                        "ent) {\r\n                    if (event.touches !== undefined) {\r\n                " +
                        "        return {\r\n                            x: event.touches[0].pageX,\r\n      " +
                        "                      y: event.touches[0].pageY\r\n                        };\r\n   " +
                        "                 }\r\n\r\n                    if (event.touches === undefined) {\r\n  " +
                        "                      if (event.pageX !== undefined) {\r\n                        " +
                        "    return {\r\n                                x: event.pageX,\r\n                 " +
                        "               y: event.pageY\r\n                            };\r\n                 " +
                        "       }\r\n                        if (event.pageX === undefined) {\r\n            " +
                        "                return {\r\n                                x: event.clientX,\r\n   " +
                        "                             y: event.clientY\r\n                            };\r\n " +
                        "                       }\r\n                    }\r\n                }\r\n\r\n          " +
                        "      function swapEvents(type) {\r\n                    if (type === \"on\") {\r\n   " +
                        "                     $(document).on(base.ev_types.move, dragMove);\r\n            " +
                        "            $(document).on(base.ev_types.end, dragEnd);\r\n                    } e" +
                        "lse if (type === \"off\") {\r\n                        $(document).off(base.ev_types" +
                        ".move);\r\n                        $(document).off(base.ev_types.end);\r\n          " +
                        "          }\r\n                }\r\n\r\n                function dragStart(event) {\r\n " +
                        "                   var ev = event.originalEvent || event || window.event,\r\n     " +
                        "                   position;\r\n\r\n                    if (ev.which === 3) {\r\n     " +
                        "                   return false;\r\n                    }\r\n                    if " +
                        "(base.itemsAmount <= base.options.items) {\r\n                        return;\r\n   " +
                        "                 }\r\n                    if (base.isCssFinish === false && !base." +
                        "options.dragBeforeAnimFinish) {\r\n                        return false;\r\n        " +
                        "            }\r\n                    if (base.isCss3Finish === false && !base.opti" +
                        "ons.dragBeforeAnimFinish) {\r\n                        return false;\r\n            " +
                        "        }\r\n\r\n                    if (base.options.autoPlay !== false) {\r\n       " +
                        "                 window.clearInterval(base.autoPlayInterval);\r\n                 " +
                        "   }\r\n\r\n                    if (base.browser.isTouch !== true && !base.$owlWrapp" +
                        "er.hasClass(\"grabbing\")) {\r\n                        base.$owlWrapper.addClass(\"g" +
                        "rabbing\");\r\n                    }\r\n\r\n                    base.newPosX = 0;\r\n    " +
                        "                base.newRelativeX = 0;\r\n\r\n                    $(this).css(base.r" +
                        "emoveTransition());\r\n\r\n                    position = $(this).position();\r\n     " +
                        "               locals.relativePos = position.left;\r\n\r\n                    locals" +
                        ".offsetX = getTouches(ev).x - position.left;\r\n                    locals.offsetY" +
                        " = getTouches(ev).y - position.top;\r\n\r\n                    swapEvents(\"on\");\r\n\r\n" +
                        "                    locals.sliding = false;\r\n                    locals.targetEl" +
                        "ement = ev.target || ev.srcElement;\r\n                }\r\n\r\n                functi" +
                        "on dragMove(event) {\r\n                    var ev = event.originalEvent || event " +
                        "|| window.event,\r\n                        minSwipe,\r\n                        max" +
                        "Swipe;\r\n\r\n                    base.newPosX = getTouches(ev).x - locals.offsetX;\r" +
                        "\n                    base.newPosY = getTouches(ev).y - locals.offsetY;\r\n        " +
                        "            base.newRelativeX = base.newPosX - locals.relativePos;\r\n\r\n          " +
                        "          if (typeof base.options.startDragging === \"function\" && locals.draggin" +
                        "g !== true && base.newRelativeX !== 0) {\r\n                        locals.draggin" +
                        "g = true;\r\n                        base.options.startDragging.apply(base, [base." +
                        "$elem]);\r\n                    }\r\n\r\n                    if ((base.newRelativeX > " +
                        "8 || base.newRelativeX < -8) && (base.browser.isTouch === true)) {\r\n            " +
                        "            if (ev.preventDefault !== undefined) {\r\n                            " +
                        "ev.preventDefault();\r\n                        } else {\r\n                        " +
                        "    ev.returnValue = false;\r\n                        }\r\n                        " +
                        "locals.sliding = true;\r\n                    }\r\n\r\n                    if ((base.n" +
                        "ewPosY > 10 || base.newPosY < -10) && locals.sliding === false) {\r\n             " +
                        "           $(document).off(\"touchmove.owl\");\r\n                    }\r\n\r\n         " +
                        "           minSwipe = function () {\r\n                        return base.newRela" +
                        "tiveX / 5;\r\n                    };\r\n\r\n                    maxSwipe = function ()" +
                        " {\r\n                        return base.maximumPixels + base.newRelativeX / 5;\r\n" +
                        "                    };\r\n\r\n                    base.newPosX = Math.max(Math.min(b" +
                        "ase.newPosX, minSwipe()), maxSwipe());\r\n                    if (base.browser.sup" +
                        "port3d === true) {\r\n                        base.transition3d(base.newPosX);\r\n  " +
                        "                  } else {\r\n                        base.css2move(base.newPosX);" +
                        "\r\n                    }\r\n                }\r\n\r\n                function dragEnd(e" +
                        "vent) {\r\n                    var ev = event.originalEvent || event || window.eve" +
                        "nt,\r\n                        newPosition,\r\n                        handlers,\r\n  " +
                        "                      owlStopEvent;\r\n\r\n                    ev.target = ev.target" +
                        " || ev.srcElement;\r\n\r\n                    locals.dragging = false;\r\n\r\n          " +
                        "          if (base.browser.isTouch !== true) {\r\n                        base.$ow" +
                        "lWrapper.removeClass(\"grabbing\");\r\n                    }\r\n\r\n                    " +
                        "if (base.newRelativeX < 0) {\r\n                        base.dragDirection = base." +
                        "owl.dragDirection = \"left\";\r\n                    } else {\r\n                     " +
                        "   base.dragDirection = base.owl.dragDirection = \"right\";\r\n                    }" +
                        "\r\n\r\n                    if (base.newRelativeX !== 0) {\r\n                        " +
                        "newPosition = base.getNewPosition();\r\n                        base.goTo(newPosit" +
                        "ion, false, \"drag\");\r\n                        if (locals.targetElement === ev.ta" +
                        "rget && base.browser.isTouch !== true) {\r\n                            $(ev.targe" +
                        "t).on(\"click.disable\", function (ev) {\r\n                                ev.stopI" +
                        "mmediatePropagation();\r\n                                ev.stopPropagation();\r\n " +
                        "                               ev.preventDefault();\r\n                           " +
                        "     $(ev.target).off(\"click.disable\");\r\n                            });\r\n      " +
                        "                      handlers = $._data(ev.target, \"events\").click;\r\n          " +
                        "                  owlStopEvent = handlers.pop();\r\n                            ha" +
                        "ndlers.splice(0, 0, owlStopEvent);\r\n                        }\r\n                 " +
                        "   }\r\n                    swapEvents(\"off\");\r\n                }\r\n               " +
                        " base.$elem.on(base.ev_types.start, \".owl-wrapper\", dragStart);\r\n            },\r" +
                        "\n\r\n            getNewPosition: function () {\r\n                var base = this,\r\n" +
                        "                    newPosition = base.closestItem();\r\n\r\n                if (new" +
                        "Position > base.maximumItem) {\r\n                    base.currentItem = base.maxi" +
                        "mumItem;\r\n                    newPosition = base.maximumItem;\r\n                }" +
                        " else if (base.newPosX >= 0) {\r\n                    newPosition = 0;\r\n          " +
                        "          base.currentItem = 0;\r\n                }\r\n                return newPo" +
                        "sition;\r\n            },\r\n            closestItem: function () {\r\n               " +
                        " var base = this,\r\n                    array = base.options.scrollPerPage === tr" +
                        "ue ? base.pagesInArray : base.positionsInArray,\r\n                    goal = base" +
                        ".newPosX,\r\n                    closest = null;\r\n\r\n                $.each(array, " +
                        "function (i, v) {\r\n                    if (goal - (base.itemWidth / 20) > array[" +
                        "i + 1] && goal - (base.itemWidth / 20) < v && base.moveDirection() === \"left\") {" +
                        "\r\n                        closest = v;\r\n                        if (base.options" +
                        ".scrollPerPage === true) {\r\n                            base.currentItem = $.inA" +
                        "rray(closest, base.positionsInArray);\r\n                        } else {\r\n       " +
                        "                     base.currentItem = i;\r\n                        }\r\n         " +
                        "           } else if (goal + (base.itemWidth / 20) < v && goal + (base.itemWidth" +
                        " / 20) > (array[i + 1] || array[i] - base.itemWidth) && base.moveDirection() ===" +
                        " \"right\") {\r\n                        if (base.options.scrollPerPage === true) {\r" +
                        "\n                            closest = array[i + 1] || array[array.length - 1];\r" +
                        "\n                            base.currentItem = $.inArray(closest, base.position" +
                        "sInArray);\r\n                        } else {\r\n                            closes" +
                        "t = array[i + 1];\r\n                            base.currentItem = i + 1;\r\n      " +
                        "                  }\r\n                    }\r\n                });\r\n               " +
                        " return base.currentItem;\r\n            },\r\n\r\n            moveDirection: function" +
                        " () {\r\n                var base = this,\r\n                    direction;\r\n       " +
                        "         if (base.newRelativeX < 0) {\r\n                    direction = \"right\";\r" +
                        "\n                    base.playDirection = \"next\";\r\n                } else {\r\n   " +
                        "                 direction = \"left\";\r\n                    base.playDirection = \"" +
                        "prev\";\r\n                }\r\n                return direction;\r\n            },\r\n\r\n" +
                        "            customEvents: function () {\r\n                /*jslint unparam: true*" +
                        "/\r\n                var base = this;\r\n                base.$elem.on(\"owl.next\", f" +
                        "unction () {\r\n                    base.next();\r\n                });\r\n           " +
                        "     base.$elem.on(\"owl.prev\", function () {\r\n                    base.prev();\r\n" +
                        "                });\r\n                base.$elem.on(\"owl.play\", function (event, " +
                        "speed) {\r\n                    base.options.autoPlay = speed;\r\n                  " +
                        "  base.play();\r\n                    base.hoverStatus = \"play\";\r\n                " +
                        "});\r\n                base.$elem.on(\"owl.stop\", function () {\r\n                  " +
                        "  base.stop();\r\n                    base.hoverStatus = \"stop\";\r\n                " +
                        "});\r\n                base.$elem.on(\"owl.goTo\", function (event, item) {\r\n       " +
                        "             base.goTo(item);\r\n                });\r\n                base.$elem.o" +
                        "n(\"owl.jumpTo\", function (event, item) {\r\n                    base.jumpTo(item);" +
                        "\r\n                });\r\n            },\r\n\r\n            stopOnHover: function () {\r" +
                        "\n                var base = this;\r\n                if (base.options.stopOnHover " +
                        "=== true && base.browser.isTouch !== true && base.options.autoPlay !== false) {\r" +
                        "\n                    base.$elem.on(\"mouseover\", function () {\r\n                 " +
                        "       base.stop();\r\n                    });\r\n                    base.$elem.on(" +
                        "\"mouseout\", function () {\r\n                        if (base.hoverStatus !== \"sto" +
                        "p\") {\r\n                            base.play();\r\n                        }\r\n    " +
                        "                });\r\n                }\r\n            },\r\n\r\n            lazyLoad: " +
                        "function () {\r\n                var base = this,\r\n                    i,\r\n       " +
                        "             $item,\r\n                    itemNumber,\r\n                    $lazyI" +
                        "mg,\r\n                    follow;\r\n\r\n                if (base.options.lazyLoad ==" +
                        "= false) {\r\n                    return false;\r\n                }\r\n              " +
                        "  for (i = 0; i < base.itemsAmount; i += 1) {\r\n                    $item = $(bas" +
                        "e.$owlItems[i]);\r\n\r\n                    if ($item.data(\"owl-loaded\") === \"loaded" +
                        "\") {\r\n                        continue;\r\n                    }\r\n\r\n              " +
                        "      itemNumber = $item.data(\"owl-item\");\r\n                    $lazyImg = $item" +
                        ".find(\".lazyOwl\");\r\n\r\n                    if (typeof $lazyImg.data(\"src\") !== \"s" +
                        "tring\") {\r\n                        $item.data(\"owl-loaded\", \"loaded\");\r\n        " +
                        "                continue;\r\n                    }\r\n                    if ($item." +
                        "data(\"owl-loaded\") === undefined) {\r\n                        $lazyImg.hide();\r\n " +
                        "                       $item.addClass(\"loading\").data(\"owl-loaded\", \"checked\");\r" +
                        "\n                    }\r\n                    if (base.options.lazyFollow === true" +
                        ") {\r\n                        follow = itemNumber >= base.currentItem;\r\n         " +
                        "           } else {\r\n                        follow = true;\r\n                   " +
                        " }\r\n                    if (follow && itemNumber < base.currentItem + base.optio" +
                        "ns.items && $lazyImg.length) {\r\n                        base.lazyPreload($item, " +
                        "$lazyImg);\r\n                    }\r\n                }\r\n            },\r\n\r\n        " +
                        "    lazyPreload: function ($item, $lazyImg) {\r\n                var base = this,\r" +
                        "\n                    iterations = 0,\r\n                    isBackgroundImg;\r\n\r\n  " +
                        "              if ($lazyImg.prop(\"tagName\") === \"DIV\") {\r\n                    $la" +
                        "zyImg.css(\"background-image\", \"url(\" + $lazyImg.data(\"src\") + \")\");\r\n           " +
                        "         isBackgroundImg = true;\r\n                } else {\r\n                    " +
                        "$lazyImg[0].src = $lazyImg.data(\"src\");\r\n                }\r\n\r\n                fu" +
                        "nction showImage() {\r\n                    $item.data(\"owl-loaded\", \"loaded\").rem" +
                        "oveClass(\"loading\");\r\n                    $lazyImg.removeAttr(\"data-src\");\r\n    " +
                        "                if (base.options.lazyEffect === \"fade\") {\r\n                     " +
                        "   $lazyImg.fadeIn(400);\r\n                    } else {\r\n                        " +
                        "$lazyImg.show();\r\n                    }\r\n                    if (typeof base.opt" +
                        "ions.afterLazyLoad === \"function\") {\r\n                        base.options.after" +
                        "LazyLoad.apply(this, [base.$elem]);\r\n                    }\r\n                }\r\n\r" +
                        "\n                function checkLazyImage() {\r\n                    iterations += " +
                        "1;\r\n                    if (base.completeImg($lazyImg.get(0)) || isBackgroundImg" +
                        " === true) {\r\n                        showImage();\r\n                    } else i" +
                        "f (iterations <= 100) {//if image loads in less than 10 seconds \r\n              " +
                        "          window.setTimeout(checkLazyImage, 100);\r\n                    } else {\r" +
                        "\n                        showImage();\r\n                    }\r\n                }\r" +
                        "\n\r\n                checkLazyImage();\r\n            },\r\n\r\n            autoHeight: " +
                        "function () {\r\n                var base = this,\r\n                    $currentimg" +
                        " = $(base.$owlItems[base.currentItem]).find(\"img\"),\r\n                    iterati" +
                        "ons;\r\n\r\n                function addHeight() {\r\n                    var $current" +
                        "Item = $(base.$owlItems[base.currentItem]).height();\r\n                    base.w" +
                        "rapperOuter.css(\"height\", $currentItem + \"px\");\r\n                    if (!base.w" +
                        "rapperOuter.hasClass(\"autoHeight\")) {\r\n                        window.setTimeout" +
                        "(function () {\r\n                            base.wrapperOuter.addClass(\"autoHeig" +
                        "ht\");\r\n                        }, 0);\r\n                    }\r\n                }\r" +
                        "\n\r\n                function checkImage() {\r\n                    iterations += 1;" +
                        "\r\n                    if (base.completeImg($currentimg.get(0))) {\r\n             " +
                        "           addHeight();\r\n                    } else if (iterations <= 100) { //i" +
                        "f image loads in less than 10 seconds \r\n                        window.setTimeou" +
                        "t(checkImage, 100);\r\n                    } else {\r\n                        base." +
                        "wrapperOuter.css(\"height\", \"\"); //Else remove height attribute\r\n                " +
                        "    }\r\n                }\r\n\r\n                if ($currentimg.get(0) !== undefined" +
                        ") {\r\n                    iterations = 0;\r\n                    checkImage();\r\n   " +
                        "             } else {\r\n                    addHeight();\r\n                }\r\n    " +
                        "        },\r\n\r\n            completeImg: function (img) {\r\n                var nat" +
                        "uralWidthType;\r\n\r\n                if (!img.complete) {\r\n                    retu" +
                        "rn false;\r\n                }\r\n                naturalWidthType = typeof img.natu" +
                        "ralWidth;\r\n                if (naturalWidthType !== \"undefined\" && img.naturalWi" +
                        "dth === 0) {\r\n                    return false;\r\n                }\r\n            " +
                        "    return true;\r\n            },\r\n\r\n            onVisibleItems: function () {\r\n " +
                        "               var base = this,\r\n                    i;\r\n\r\n                if (b" +
                        "ase.options.addClassActive === true) {\r\n                    base.$owlItems.remov" +
                        "eClass(\"active\");\r\n                }\r\n                base.visibleItems = [];\r\n " +
                        "               for (i = base.currentItem; i < base.currentItem + base.options.it" +
                        "ems; i += 1) {\r\n                    base.visibleItems.push(i);\r\n\r\n              " +
                        "      if (base.options.addClassActive === true) {\r\n                        $(bas" +
                        "e.$owlItems[i]).addClass(\"active\");\r\n                    }\r\n                }\r\n " +
                        "               base.owl.visibleItems = base.visibleItems;\r\n            },\r\n\r\n   " +
                        "         transitionTypes: function (className) {\r\n                var base = thi" +
                        "s;\r\n                //Currently available: \"fade\", \"backSlide\", \"goDown\", \"fadeU" +
                        "p\"\r\n                base.outClass = \"owl-\" + className + \"-out\";\r\n              " +
                        "  base.inClass = \"owl-\" + className + \"-in\";\r\n            },\r\n\r\n            sing" +
                        "leItemTransition: function () {\r\n                var base = this,\r\n             " +
                        "       outClass = base.outClass,\r\n                    inClass = base.inClass,\r\n " +
                        "                   $currentItem = base.$owlItems.eq(base.currentItem),\r\n        " +
                        "            $prevItem = base.$owlItems.eq(base.prevItem),\r\n                    p" +
                        "revPos = Math.abs(base.positionsInArray[base.currentItem]) + base.positionsInArr" +
                        "ay[base.prevItem],\r\n                    origin = Math.abs(base.positionsInArray[" +
                        "base.currentItem]) + base.itemWidth / 2,\r\n                    animEnd = \'webkitA" +
                        "nimationEnd oAnimationEnd MSAnimationEnd animationend\';\r\n\r\n                base." +
                        "isTransition = true;\r\n\r\n                base.$owlWrapper\r\n                    .a" +
                        "ddClass(\'owl-origin\')\r\n                    .css({\r\n                        \"-web" +
                        "kit-transform-origin\": origin + \"px\",\r\n                        \"-moz-perspective" +
                        "-origin\": origin + \"px\",\r\n                        \"perspective-origin\": origin +" +
                        " \"px\"\r\n                    });\r\n                function transStyles(prevPos) {\r" +
                        "\n                    return {\r\n                        \"position\": \"relative\",\r\n" +
                        "                        \"left\": prevPos + \"px\"\r\n                    };\r\n        " +
                        "        }\r\n\r\n                $prevItem\r\n                    .css(transStyles(pre" +
                        "vPos, 10))\r\n                    .addClass(outClass)\r\n                    .on(ani" +
                        "mEnd, function () {\r\n                        base.endPrev = true;\r\n             " +
                        "           $prevItem.off(animEnd);\r\n                        base.clearTransStyle" +
                        "($prevItem, outClass);\r\n                    });\r\n\r\n                $currentItem\r" +
                        "\n                    .addClass(inClass)\r\n                    .on(animEnd, functi" +
                        "on () {\r\n                        base.endCurrent = true;\r\n                      " +
                        "  $currentItem.off(animEnd);\r\n                        base.clearTransStyle($curr" +
                        "entItem, inClass);\r\n                    });\r\n            },\r\n\r\n            clear" +
                        "TransStyle: function (item, classToRemove) {\r\n                var base = this;\r\n" +
                        "                item.css({\r\n                    \"position\": \"\",\r\n               " +
                        "     \"left\": \"\"\r\n                }).removeClass(classToRemove);\r\n\r\n             " +
                        "   if (base.endPrev && base.endCurrent) {\r\n                    base.$owlWrapper." +
                        "removeClass(\'owl-origin\');\r\n                    base.endPrev = false;\r\n         " +
                        "           base.endCurrent = false;\r\n                    base.isTransition = fal" +
                        "se;\r\n                }\r\n            },\r\n\r\n            owlStatus: function () {\r\n" +
                        "                var base = this;\r\n                base.owl = {\r\n                " +
                        "    \"userOptions\": base.userOptions,\r\n                    \"baseElement\": base.$e" +
                        "lem,\r\n                    \"userItems\": base.$userItems,\r\n                    \"ow" +
                        "lItems\": base.$owlItems,\r\n                    \"currentItem\": base.currentItem,\r\n" +
                        "                    \"prevItem\": base.prevItem,\r\n                    \"visibleItem" +
                        "s\": base.visibleItems,\r\n                    \"isTouch\": base.browser.isTouch,\r\n  " +
                        "                  \"browser\": base.browser,\r\n                    \"dragDirection\":" +
                        " base.dragDirection\r\n                };\r\n            },\r\n\r\n            clearEven" +
                        "ts: function () {\r\n                var base = this;\r\n                base.$elem." +
                        "off(\".owl owl mousedown.disableTextSelect\");\r\n                $(document).off(\"." +
                        "owl owl\");\r\n                $(window).off(\"resize\", base.resizer);\r\n            " +
                        "},\r\n\r\n            unWrap: function () {\r\n                var base = this;\r\n     " +
                        "           if (base.$elem.children().length !== 0) {\r\n                    base.$" +
                        "owlWrapper.unwrap();\r\n                    base.$userItems.unwrap().unwrap();\r\n  " +
                        "                  if (base.owlControls) {\r\n                        base.owlContr" +
                        "ols.remove();\r\n                    }\r\n                }\r\n                base.cl" +
                        "earEvents();\r\n                base.$elem\r\n                    .attr(\"style\", bas" +
                        "e.$elem.data(\"owl-originalStyles\") || \"\")\r\n                    .attr(\"class\", ba" +
                        "se.$elem.data(\"owl-originalClasses\"));\r\n            },\r\n\r\n            destroy: f" +
                        "unction () {\r\n                var base = this;\r\n                base.stop();\r\n  " +
                        "              window.clearInterval(base.checkVisible);\r\n                base.unW" +
                        "rap();\r\n                base.$elem.removeData();\r\n            },\r\n\r\n            " +
                        "reinit: function (newOptions) {\r\n                var base = this,\r\n             " +
                        "       options = $.extend({}, base.userOptions, newOptions);\r\n                ba" +
                        "se.unWrap();\r\n                base.init(options, base.$elem);\r\n            },\r\n\r" +
                        "\n            addItem: function (htmlString, targetPosition) {\r\n                v" +
                        "ar base = this,\r\n                    position;\r\n\r\n                if (!htmlStrin" +
                        "g) { return false; }\r\n\r\n                if (base.$elem.children().length === 0) " +
                        "{\r\n                    base.$elem.append(htmlString);\r\n                    base." +
                        "setVars();\r\n                    return false;\r\n                }\r\n              " +
                        "  base.unWrap();\r\n                if (targetPosition === undefined || targetPosi" +
                        "tion === -1) {\r\n                    position = -1;\r\n                } else {\r\n  " +
                        "                  position = targetPosition;\r\n                }\r\n               " +
                        " if (position >= base.$userItems.length || position === -1) {\r\n                 " +
                        "   base.$userItems.eq(-1).after(htmlString);\r\n                } else {\r\n        " +
                        "            base.$userItems.eq(position).before(htmlString);\r\n                }\r" +
                        "\n\r\n                base.setVars();\r\n            },\r\n\r\n            removeItem: fu" +
                        "nction (targetPosition) {\r\n                var base = this,\r\n                   " +
                        " position;\r\n\r\n                if (base.$elem.children().length === 0) {\r\n       " +
                        "             return false;\r\n                }\r\n                if (targetPositio" +
                        "n === undefined || targetPosition === -1) {\r\n                    position = -1;\r" +
                        "\n                } else {\r\n                    position = targetPosition;\r\n     " +
                        "           }\r\n\r\n                base.unWrap();\r\n                base.$userItems." +
                        "eq(position).remove();\r\n                base.setVars();\r\n            }\r\n\r\n      " +
                        "  };\r\n\r\n        $.fn.owlCarousel = function (options) {\r\n            return this" +
                        ".each(function () {\r\n                if ($(this).data(\"owl-init\") === true) {\r\n " +
                        "                   return false;\r\n                }\r\n                $(this).dat" +
                        "a(\"owl-init\", true);\r\n                var carousel = Object.create(Carousel);\r\n " +
                        "               carousel.init(options, this);\r\n                $.data(this, \"owlC" +
                        "arousel\", carousel);\r\n            });\r\n        };\r\n\r\n        $.fn.owlCarousel.op" +
                        "tions = {\r\n\r\n            items: 4,\r\n            itemsCustom: false,\r\n           " +
                        " itemsDesktop: [1199, 4],\r\n            itemsDesktopSmall: [979, 3],\r\n           " +
                        " itemsTablet: [768, 2],\r\n            itemsTabletSmall: false,\r\n            items" +
                        "Mobile: [479, 1],\r\n            singleItem: false,\r\n            itemsScaleUp: fal" +
                        "se,\r\n\r\n            slideSpeed: 200,\r\n            paginationSpeed: 800,\r\n        " +
                        "    rewindSpeed: 1000,\r\n\r\n            autoPlay: true,\r\n            stopOnHover: " +
                        "true,\r\n\r\n            navigation: false,\r\n            navigationText: [\"prev\", \"n" +
                        "ext\"],\r\n            rewindNav: true,\r\n            scrollPerPage: false,\r\n\r\n     " +
                        "       pagination: true,\r\n            paginationNumbers: false,\r\n\r\n            r" +
                        "esponsive: true,\r\n            responsiveRefreshRate: 200,\r\n            responsiv" +
                        "eBaseWidth: window,\r\n\r\n            baseClass: \"owl-carousel\",\r\n            theme" +
                        ": \"owl-theme\",\r\n\r\n            lazyLoad: false,\r\n            lazyFollow: true,\r\n " +
                        "           lazyEffect: \"fade\",\r\n\r\n            autoHeight: false,\r\n\r\n            " +
                        "jsonPath: false,\r\n            jsonSuccess: false,\r\n\r\n            dragBeforeAnimF" +
                        "inish: true,\r\n            mouseDrag: true,\r\n            touchDrag: true,\r\n\r\n    " +
                        "        addClassActive: false,\r\n            transitionStyle: false,\r\n\r\n         " +
                        "   beforeUpdate: false,\r\n            afterUpdate: false,\r\n            beforeInit" +
                        ": false,\r\n            afterInit: false,\r\n            beforeMove: false,\r\n       " +
                        "     afterMove: false,\r\n            afterAction: false,\r\n            startDraggi" +
                        "ng: false,\r\n            afterLazyLoad: false\r\n        };\r\n    }(jQuery, window, " +
                        "document));\r\n\r\n</script>\r\n\r\n<style type=\"text/css\">\r\n.owl-carousel .owl-wrapper:" +
                        "after {\r\n\tcontent: \".\";\r\n\tdisplay: block;\r\n\tclear: both;\r\n\tvisibility: hidden;\r\n" +
                        "\tline-height: 0;\r\n\theight: 0;\r\n}\r\n/* display none until init */\r\n.owl-carousel{\r" +
                        "\n\tdisplay: none;\r\n\tposition: relative;\r\n\twidth: 100%;\r\n\t-ms-touch-action: pan-y;" +
                        "\r\n}\r\n.owl-carousel .owl-wrapper{\r\n\tdisplay: none;\r\n\tposition: relative;\r\n\t-webki" +
                        "t-transform: translate3d(0px, 0px, 0px);\r\n}\r\n.owl-carousel .owl-wrapper-outer{\r\n" +
                        "\toverflow: hidden;\r\n\tposition: relative;\r\n\twidth: 100%;\r\n}\r\n.owl-carousel .owl-w" +
                        "rapper-outer.autoHeight{\r\n\t-webkit-transition: height 500ms ease-in-out;\r\n\t-moz-" +
                        "transition: height 500ms ease-in-out;\r\n\t-ms-transition: height 500ms ease-in-out" +
                        ";\r\n\t-o-transition: height 500ms ease-in-out;\r\n\ttransition: height 500ms ease-in-" +
                        "out;\r\n}\r\n\t\r\n.owl-carousel .owl-item{\r\n\tfloat: left;\r\n}\r\n.owl-controls .owl-page," +
                        "\r\n.owl-controls .owl-buttons div{\r\n\tcursor: pointer;\r\n}\r\n.owl-controls {\r\n\t-webk" +
                        "it-user-select: none;\r\n\t-khtml-user-select: none;\r\n\t-moz-user-select: none;\r\n\t-m" +
                        "s-user-select: none;\r\n\tuser-select: none;\r\n\t-webkit-tap-highlight-color: rgba(0," +
                        " 0, 0, 0);\r\n}\r\n\r\n/* mouse grab icon */\r\n.grabbing { \r\n    cursor:url(grabbing.pn" +
                        "g) 8 8, move;\r\n}\r\n\r\n/* fix */\r\n.owl-carousel  .owl-wrapper,\r\n.owl-carousel  .owl" +
                        "-item{\r\n\t-webkit-backface-visibility: hidden;\r\n\t-moz-backface-visibility:    hid" +
                        "den;\r\n\t-ms-backface-visibility:     hidden;\r\n  -webkit-transform: translate3d(0," +
                        "0,0);\r\n  -moz-transform: translate3d(0,0,0);\r\n  -ms-transform: translate3d(0,0,0" +
                        ");\r\n}\r\n\r\n</style>\r\n\r\n<style type=\"text/css\">\r\n    /*\r\n* \tOwl Carousel Owl Demo T" +
                        "heme \r\n*\tv1.3.3\r\n*/\r\n\r\n.owl-theme .owl-controls{\r\n\tmargin-top: 10px;\r\n\ttext-alig" +
                        "n: center;\r\n}\r\n\r\n/* Styling Next and Prev buttons */\r\n\r\n.owl-theme .owl-controls" +
                        " .owl-buttons div{\r\n\tcolor: #FFF;\r\n\tdisplay: inline-block;\r\n\tzoom: 1;\r\n\t*display" +
                        ": inline;/*IE7 life-saver */\r\n\tmargin: 5px;\r\n\tpadding: 3px 10px;\r\n\tfont-size: 12" +
                        "px;\r\n\t-webkit-border-radius: 30px;\r\n\t-moz-border-radius: 30px;\r\n\tborder-radius: " +
                        "30px;\r\n\tbackground: #869791;\r\n\tfilter: Alpha(Opacity=100);/*IE7 fix*/\r\n\topacity:" +
                        " 1;\r\n}\r\n/* Clickable class fix problem with hover on touch devices */\r\n/* Use it" +
                        " for non-touch hover action */\r\n.owl-theme .owl-controls.clickable .owl-buttons " +
                        "div:hover{\r\n\tfilter: Alpha(Opacity=50);/*IE7 fix*/\r\n\topacity: 0.5;\r\n\ttext-decora" +
                        "tion: none;\r\n}\r\n\r\n/* Styling Pagination*/\r\n\r\n.owl-theme .owl-controls .owl-page{" +
                        "\r\n\tdisplay: inline-block;\r\n\tzoom: 1;\r\n\t*display: inline;/*IE7 life-saver */\r\n}\r\n" +
                        ".owl-theme .owl-controls .owl-page span{\r\n\tdisplay: block;\r\n\twidth: 12px;\r\n\theig" +
                        "ht: 12px;\r\n\tmargin: 5px 7px;\r\n\tfilter: Alpha(Opacity=50);/*IE7 fix*/\r\n\topacity: " +
                        "0.5;\r\n\t-webkit-border-radius: 20px;\r\n\t-moz-border-radius: 20px;\r\n\tborder-radius:" +
                        " 20px;\r\n\tbackground: #ba4c34;\r\n}\r\n\r\n.owl-theme .owl-controls .owl-page.active sp" +
                        "an,\r\n.owl-theme .owl-controls.clickable .owl-page:hover span{\r\n\tfilter: Alpha(Op" +
                        "acity=100);/*IE7 fix*/\r\n\topacity: 1;\r\n}\r\n\r\n/* If PaginationNumbers is true */\r\n\r" +
                        "\n.owl-theme .owl-controls .owl-page span.owl-numbers{\r\n\theight: auto;\r\n\twidth: a" +
                        "uto;\r\n\tcolor: #FFF;\r\n\tpadding: 2px 10px;\r\n\tfont-size: 12px;\r\n\t-webkit-border-rad" +
                        "ius: 30px;\r\n\t-moz-border-radius: 30px;\r\n\tborder-radius: 30px;\r\n}\r\n\r\n/* preloadin" +
                        "g images */\r\n.owl-item.loading{\r\n\tmin-height: 150px;\r\n\tbackground: url(AjaxLoade" +
                        "r.gif) no-repeat center center\r\n}\r\n\r\n</style>\r\n<style type=\"text/css\">\r\n.promoIt" +
                        "em\r\n{\r\n\tfont-family:Arial, Helvetica, sans-serif;\r\n\theight:200px;\r\n\tpadding:5px;" +
                        "\r\n\tpadding-bottom:0px;\r\n}\r\n\r\n.promoBox\r\n{\r\n\tdisplay:block;\r\nheight:100%;\r\nwidth:" +
                        "100%;\r\n}\r\n\r\n.promoBox img\r\n{\r\n\tposition:relative;\r\n\twidth:100%;\r\n\theight:100%;\r\n" +
                        "\tz-index:-1;\r\n\tpadding:0;\r\n}\r\n.textdiv\r\n{\r\n\t\r\n\theight:95px;\r\n\tcolor:white;\r\n\tpad" +
                        "ding:3px;\r\n\t\r\n\tmargin-top:-95px;\r\n\tbackground: url(\'/_catalogs/masterpage/images" +
                        "/transparent-bg.png\');\r\n}\r\n\r\n.textdiv h3\r\n{\r\ncolor:white;\r\n\tmargin:0;\r\n\tfont-siz" +
                        "e:14px;\r\n}\r\n.textdiv h4\r\n{\r\ncolor:white;\r\n\tfont-size:10px;\r\n\tmargin:0;\r\n\ttext-de" +
                        "coration:none;\r\n}\r\n.textdiv h4 a:link\r\n{\r\n\ttext-decoration:none;\r\n}\r\n\r\na:-webkit" +
                        "-any-link\r\n{\r\n\ttext-decoration:none;\r\n}\r\n.owl-theme .owl-controls .owl-buttons d" +
                        "iv\r\n{\r\n\t-webkit-border-radius: 0px;\r\n-moz-border-radius: 0px;\r\nborder-radius: 0p" +
                        "x;\r\n}\r\n\r\n.owl-theme .owl-controls .owl-buttons div\r\n{\r\n\tfont-family:Arial, Helve" +
                        "tica, sans-serif;\r\n\tbackground-color:#ba4c34;\r\n\tfilter: Alpha(Opacity=100);\r\n}\r\n" +
                        "\r\n.owl-theme .owl-controls .owl-page.active span, .owl-theme .owl-controls.click" +
                        "able .owl-page:hover span\r\n{\r\n\tbackground:#ba4c34;\r\n}\r\n\r\n</style>\r\n</head>\r\n<bod" +
                        "y>\r\n<div>\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlPromoItemsContainer();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  \t\r\n\r\n\r\n\r\n\r\n</div>\r\n\r\n\r\n\r\n\r\n<script type=\"text/javascript\">\r\n    $(document).r" +
                        "eady(function () {\r\n\r\n        $(\"#owl-example\").owlCarousel();\r\n    });\r\n</scrip" +
                        "t>\r\n\r\n\r\n</body>\r\n\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
