//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingListWebpart.VisualWebPart1 {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class VisualWebPart1 {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTable meetingTable;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(VisualWebPart1 target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTable @__BuildControlmeetingTable() {
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTable();
            this.meetingTable = @__ctrl;
            @__ctrl.ID = "meetingTable";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::MeetingListWebpart.VisualWebPart1.VisualWebPart1 @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<head>\r\n    <script src=\"http://wdcdmzsp4/business/SiteAssets/jquery.js\"></scri" +
                        "pt>\r\n<title>Meetings Webpart</title>\r\n    <script type=\"text/javascript\">\r\n     " +
                        "   function displayMeetingLocation(iframeCode)\r\n        {\r\n            //$(\"meet" +
                        "ing-location-popup\").html(iframeCode).text();\r\n            var popuplocation = d" +
                        "ocument.getElementById(\"meeting-location-popup\");\r\n            popuplocation.inn" +
                        "erHTML = iframeCode;\r\n\r\n            var popupcontainer = document.getElementById" +
                        "(\"meeting-location-container-popup\");\r\n            popupcontainer.style.display " +
                        "=    \'block\';\r\n        }\r\n        function hidelocationpopup()\r\n        {\r\n     " +
                        "       var lpop = document.getElementById(\"meeting-location-container-popup\");\r\n" +
                        "            lpop.style.display = \'none\';\r\n        }\r\n    </script>\r\n<style>\r\n#Me" +
                        "etingContainer \r\n{\r\n\ttext-align:center;\r\n\tfont-family:Arial;\r\n\twidth:100%;\r\n}\r\n\r" +
                        "\n#MeetingContainer table tr\r\n{\r\n\r\n\tmargin-top:5px;\r\n}\r\n#MeetingContainer table \r" +
                        "\n{\r\n    border: 1px solid #666280;\r\n\twidth:100%;\r\n    max-width:700px;\r\n\tborder-" +
                        "collapse:separate;\r\n    margin-left:auto;\r\n    margin-right:auto;\r\n\r\n\r\n}\r\n#Meeti" +
                        "ngContainer .edges\r\n\t{\r\n\t\tmargin:0;\r\n\t\tpadding:0;\r\n\t\ttext-align:center;\r\n\t\tfont-" +
                        "size:10px;\r\n\t\tcolor:white;\r\n\t\twidth:22%;\r\n\t\theight:150px;\r\n\t\tbackground: rgb(102" +
                        ",98,128); \r\n\r\n\t}\r\n#MeetingContainer .edges h1,#MeetingContainer .edges h2\r\n\t{\r\n " +
                        "       color:white;\r\n\t\tpadding:0;\r\n\t\tmargin:0;\r\n\t}\r\n#MeetingContainer .middlecel" +
                        "l\r\n\t{\r\n    padding-left:5px;\r\n    padding-right:5px;\r\n\t\ttext-align:left;\r\n\t\twidt" +
                        "h:56%;\r\n\t\tborder-width:1px;\r\n\t\tborder-style:solid;\r\n\t\tborder-color:rgb(102,98,12" +
                        "8);\r\n\t\tborder-bottom-width:1px;\r\n\t\tborder-bottom-style:solid;\r\n\t\tborder-bottom-c" +
                        "olor:rgb(102,98,128);\r\n\r\n\t}\r\n\t\r\n\t#MeetingContainer table tr > td\r\n{\r\n  margin-bo" +
                        "ttom: 1em;\r\n}\r\n#MeetingContainer a\r\n{\r\n\tfont-size:8px;\r\n}\r\n#MeetingContainer .ce" +
                        "nter\r\n{\r\n\tfont-weight:normal;\r\n\tline-height:80px;\r\n}\r\n\r\n.meeting-location-popup " +
                        "{\r\n    width: 50%;\r\n    height: 50%;\r\n    background: #1abcb9;\r\n    position: ab" +
                        "solute;\r\n    top: 0;\r\n    right: 0;\r\n    bottom: 0;\r\n    left: 0;\r\n    margin: a" +
                        "uto;\r\n}\r\n\r\n.meeting-location-container-popup {\r\n    display:none;\r\n    position:" +
                        " fixed;\r\n    top: 0;\r\n    right: 0;\r\n    bottom: 0;\r\n    left: 0;\r\n    backgroun" +
                        "d: rgba(0,0,0,.8);\r\n}\r\n</style>\r\n\r\n</head>\r\n\r\n<body>\r\n\t<div id=\"MeetingContainer" +
                        "\">\r\n\t\t"));
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl1;
            @__ctrl1 = this.@__BuildControlmeetingTable();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t</div>\r\n    <div id=\"meeting-location-container-popup\" class=\"meeting-location" +
                        "-container-popup\" onclick=\"hidelocationpopup()\'>\r\n    <div id=\"meeting-location-" +
                        "popup\" class=\"meeting-location-popup\"></div>\r\n</div>\r\n</body>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
